const quotes = [
  'Utoljára egy kannibál törzs étlapján említették a nevét valami savanykás körettel kapcsolatban.',
  'Eztet a szót speciel, hogy kísértet soha ne mondja hajón. Én nem vagyok babonás és nem hiszek a badarságokban, mert aki minden hétfőn hármat köp kelet felé egy barna kavicsra, azt nem érheti megrontás.',
  'Hideg pakolásban megkövetelem a Priznic of Wales címet.',
  'Az asszony szíve éppolyan, mint a tenger: nyugodtan, simán dobog, de senki sem lát a mélyére, és ha igen, úgy annak jaj.',
  'A titok éltető elem, természetesen kiválasztódó ellenmérge a valóság ciánkálijának.',
  'A művelt emberiségnek üzenem: Mindenütt jó, de legjobb a Horchman-pneu és tömlő, ugyanott elsőrangú golyóscsapágy!',
  'Valaki azt mondja, hogy két cápa úszott már a fiú felé, de amikor meglátták a kapitányt, csüggedten visszafordultak.',
  'Csak egy asszony építheti fel újra, amit egy másik asszony romba döntött.',
  'A közügy mindenkinek kedvenc magánügye.',
  'Vasárnap ne lopj, ne verj meg senkit, mert hat nap mindenre elegendő.',
  'Munka után édes a menekülés.',
  'Mit csinál az ember, aki felhagy minden reménnyel? Megmondta Dante. Elmegy a pokolba.',
  'Legszebb élet az artista aranyöregsége. Mert szakmánkban fordított értelme van a kornak. Amíg az artista fiatal, addig közel áll a halálhoz. Minden este meghalhat, és esetleg délután is, mérsékelt helyárak mellett.',
  'Mindenki onnan jön, ahonnan akar, vagy ahonnan szabadon bocsátják.',
  'Az igazság... sokszor titokban marad... De az igazságtalanság... mindég kiderül... A többit majd odafenn... zárt tárgyaláson.',
  'A legnagyobb úrral is könnyű beszélni, ha nem a hivatalában keresik fel. Irodában senki sem szeret hivatalos ügyekkel foglalkozni.',
  'A kikötő olyan, mint a dzsungel, csak nem terem annyi fa benne. De sokkal veszélyesebb. Tele van hajóval meg verekedéssel.',
  'Rájöttem, hogy uralkodni nem is nehéz, csak trónhoz jusson az ember ebbe a tolongásba.',
  'Maga jobban tenné, ha elmenne csomagot hordani, nagy, erős ember, hogy sülne ki a szeme, csak lopja a napot, meg ki tudja, mi mindent.',
  'Mert ha a Török Szultán nadrágját nem lopják el, vagy ha Tuskó Hopkins jobban ügyel a saját ruházatára, akkor néhány ember, sőt egy kis birodalom sorsa is másképpen alakul. Ilyen rejtélyek húzódnak meg olykor egy nadrág hátterében.',
  'Barátaim és tisztelőim általában hülyének tartanak. Nem vagyok elmeorvos, tehát nem tudom ellenőrizni őket.',
  'Maga olyan nagy állat, hogy vadászni kellene.',
  'A kíváncsi turista olyan, mint a szerelmes férj. Mindent elhisz és semmit sem lát.',
  'Az nevet, aki először üt.',
  'Korán kelni: fél árulás! Aki korán kel, az aranyat akar lelni. Nem? Aki aranyat lelne, az gyanús, mert szívesen válna tőkepénzessé. De kire lehet az ilyesmit rábizonyítani? Ne vádaskodjunk vaktában.',
  'Belépés díjtalan, kilépés bizonytalan!',
  'Ide hallgasson, rablovics úr.',
  'Az élet olyan, mint egy nyári ruha mellénye: rövid és céltalan.',
  'Galamb nekirepült a falnak, de a következő pillanatban már úgy vágta szájon a vitorlamestert, hogy ez meglepetésében lenyelt egy negyed font bagót, ami a szájában volt, és percekig csuklott utána.'
]
