const text = [

  "A közügy mindenkinek kedvenc magánügye.",
  "Vasárnap ne lopj, ne verj meg senkit, mert hat nap mindenre elegendő.",
  "Nem olyan tehetséges a világ, hogy néhány okos ember ne tudná becsapni.",
  "Munka után édes a menekülés.",
  "A titok éltető elem, természetesen kiválasztódó ellenmérge a valóság ciánkálijának.",
  "Csak egy asszony építheti fel újra, amit egy másik asszony romba döntött.",
  "Nem a végső siker a diadal, hanem az első.",
  "Akkor kell felugrani a szerencse vonatára, amikor éppen elrohan melletted, mindegy, hogy merre visz, mert egy elhibázott, elhabozott ugrás, és egész életeden át hiába vársz másik vonatra.",
  "Tévedni emberi dolog, de azért velem is előfordulhat.",
  "Ha az ember igazán hisz valamiben, esetleg az sem baj, ha nem igaz. Sokszor a puszta hit is lehet igazi nagy ajándék.",
  "Rémes, hogy milyen szűk viselet más ember életét hordani.",
  "Mit csinál az ember, aki felhagy minden reménnyel? Megmondta Dante. Elmegy a pokolba.",
  "Az igazság, ha elfojtják, lassan ható méreg. Már vastag börtönfalakon, ránehezedő évszázadokon is keresztülrágta magát.",
  "Ó Uram! De nagy vagy! És micsoda színpadi rendező veszett el a sorsban!",
  "A sors olyan, mint egy részeges szabász: mikor belevág a szövetbe, még nem lehet tudni: felöltő lesz-e belőle vagy nadrág.",
  "Legszebb élet az artista aranyöregsége. Mert szakmánkban fordított értelme van a kornak. Amíg az artista fiatal, addig közel áll a halálhoz. Minden este meghalhat, és esetleg délután is, mérsékelt helyárak mellett.",
  "A szenzáció az, ami összeköt látszólag egymástól távol álló eseményeket.",
  "Kit érdekel manapság, amit írnak? A kor nyelve a fotó.",
  "Mindenki onnan jön, ahonnan akar, vagy ahonnan szabadon bocsátják.",
  "Az igazság... sokszor titokban marad... De az igazságtalanság... mindég kiderül... A többit majd odafenn... zárt tárgyaláson.",
  "Bizonyos relációk alacsony értékén az élet semmilyen közbenjárása nem változtat.",
  "A legnagyobb úrral is könnyű beszélni, ha nem a hivatalában keresik fel. Irodában senki sem szeret hivatalos ügyekkel foglalkozni.",
  "Az asszony szíve éppolyan, mint a tenger: nyugodtan, simán dobog, de senki sem lát a mélyére, és ha igen, úgy annak jaj.",
  "Az igazságot nem lehet hinni... Azt tudni kell, vagy hagyni. De ez a világ a dilettánsoké.",
  "A vörösbor fáj, de azt mondja: \"Jó lenne élni!\" Ha többet iszol, így szól: \"Élni kell!\" Ha igen sokat iszol, ezt kiáltja: \"Élni fogsz!\" És ez akkor is szép, ha nem igaz.",
  "A pénz az egyetlen jó, amiből nem árt a sok.",
  "A kikötő olyan, mint a dzsungel, csak nem terem annyi fa benne. De sokkal veszélyesebb. Tele van hajóval meg verekedéssel.",
  "Hogy is van a csavargók nagy mondása? \"Mindenütt jó, de legjobb sehol!\"",
  "Rájöttem, hogy uralkodni nem is nehéz, csak trónhoz jusson az ember ebbe a tolongásba. Mer az egész világ olyan mint egy nagy tolongás: hol elől van az ember, hol hátul.",
  "Többet ér egy megtért bűnös száz igaz hívőnél.",
  "Az életben csak pozőrök számára fordulnak elő komoly dolgok.",
  "A művelt emberiségnek üzenem: Mindenütt jó, de legjobb a Horchman-pneu és tömlő, ugyanott elsőrangú golyóscsapágy!",
  "Maga jobban tenné, ha elmenne csomagot hordani, nagy, erős ember, hogy sülne ki a szeme, csak lopja a napot, meg ki tudja, mi mindent.",
  "Minden valótlan tény felismerése egy lépéssel közelebb visz a való tényálláshoz.",
  "Grófnő, egy okos embert csak kétszer lehet becsapni!",
  "Mert ha a Török Szultán nadrágját nem lopják el, vagy ha Tuskó Hopkins jobban ügyel a saját ruházatára, akkor néhány ember, sőt egy kis birodalom sorsa is másképpen alakul. Ilyen rejtélyek húzódnak meg olykor egy nadrág hátterében.",
  "Hideg pakolásban megkövetelem a Priznic of Wales címet.",
  "Eztet a szót speciel, hogy kísértet soha ne mondja hajón. Én nem vagyok babonás és nem hiszek a badarságokban, mert aki minden hétfőn hármat köp kelet felé egy barna kavicsra, azt nem érheti megrontás.",
  "Aki itt erős akar lenni, az úgy jár mint a vas. Eszt úgy értik, hogy addig lesz ütve, amíg meleg. Nem üres felírás.",
  "Barátaim és tisztelőim általában hülyének tartanak. Nem vagyok elmeorvos, tehát nem tudom ellenőrizni őket.",
  "A fillérből sohasem lesz korona. Fillérből sóhajtozás lesz, gond, örlődés, beosztás, fejtörés.",
  "Amíg pokol van, addig megfelelő ördögöt is találnak.",
  "Maga olyan nagy állat, hogy vadászni kellene.",
  "A bolond ember eléggé logikus, csak az épelméjűek bírálata felületes.",
  "A kíváncsi turista olyan, mint a szerelmes férj. Mindent elhisz és semmit sem lát.",
  "Az nevet, aki először üt."
  "Aki korán kel, az aranyat akar lelni. Nem? Aki aranyat lelne, az gyanús, mert szívesen válna tőkepénzessé. De kire lehet az ilyesmit rábizonyítani? Ne vádaskodjunk vaktában.",
  "Egy igazság akkor is fontos, ha nincs semmi értelme.",
  "A kitalált hazugság soha nem ér annyit, mint az ügyes igazmondás.",
  "Az ellenszenvet és baráti érzést legtöbbször nem az okszerűség szövi az emberek között.",
  "Aki soká tétovázik, az hamarabb szab el egy ruhát, mint aki bátran vág bele a szövetbe.",
  "Életünk legfontosabb eseményei a látványos okokon kívül tulajdonképpen ellenőrizhetetlen semmiségekre vezethetők vissza.",
  "Bocsánat, hogy félbeszakítom, de nem értek a földrajzhoz: hogy tud Afrika csókolni?",
  "Akik a legnagyobb mesterektől tanulnak bölcsen gondolkozni, azoknak általában a legritkább esetben jut az eszükbe olyasvalami, aminek hasznát vehetik.",
  "Utoljára egy kannibál törzs étlapján említették a nevét valami savanykás körettel kapcsolatban."

]
